-- C autoload
-- vim.keymap.set("i", '<C-P>', 'printf("\\n");<Esc>4hi')
-- vim.keymap.set("", '<C-P>', 'aprintf("\\n");<Esc>4hi')
-- vim.keymap.set("", '<C-O>', 'oprintf("\\n");<Esc>4hi')
-- vim.keymap.set("i", '<C-O>', 'printf("\\n");<Esc>4hi')
